name: GRNITE
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.7.14
  - cairo=1.16.0
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - debugpy=1.8.11
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - fribidi=1.0.10
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - importlib-metadata=8.7.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.1.1
  - libcups=2.4.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.84.2
  - libgomp=11.2.0
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mysql=8.4.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numexpr=2.11.0
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.16
  - packaging=24.2
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.1
  - pixman=0.40.0
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.11.13
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - pyzmq=26.2.0
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.3
  - seaborn=0.13.2
  - setuptools=78.1.1
  - sip=6.10.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - tzdata=2025b
  - unicodedata2=15.1.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-renderutil=0.3.10
  - xkeyboard-config=2.44
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - anndata==0.12.1
      - array-api-compat==1.12.0
      - attrs==25.3.0
      - blosc2==3.5.1
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - crc32c==2.7.1
      - donfig==0.8.1.post1
      - et-xmlfile==2.0.0
      - filelock==3.13.1
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - h5py==3.14.0
      - idna==3.10
      - jinja2==3.1.6
      - legacy-api-wrap==1.4.1
      - llvmlite==0.44.0
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.3
      - natsort==8.4.0
      - ndindex==1.10.0
      - numba==0.61.2
      - numcodecs==0.16.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - openpyxl==3.1.5
      - pandas==2.3.1
      - patsy==1.0.1
      - propcache==0.3.2
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pynndescent==0.5.13
      - pyyaml==6.0.2
      - requests==2.32.4
      - scanpy==1.11.4
      - session-info2==0.2
      - statsmodels==0.14.5
      - sympy==1.13.1
      - tables==3.10.2
      - torch==2.5.1+cu121
      - torch-geometric==2.6.1
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - triton==3.1.0
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - yarl==1.20.1
      - zarr==3.1.1
prefix: /opt/anaconda3/envs/env_grn
